a = ('Botafogo','Palmeiras','Fortaleza','Flamengo','São Paulo','Internacional','Bahia','Cruzeiro','Atletico-Mg','Vasco','Criciuma','Gremio','Fluminense','Bragantino','Juventude','EC Vitoria','Athletico-PR','Corinthians','Cuiabá','Atlético-GO')
print('-='*30)
print(a[:5])
print('-='*30)
print(a[-4:])
print('-='*30)
print(sorted(a))
print('-='*30)
print(f'O Cruzeiro está na {a.index("Cruzeiro")+1} posição.')
print('-='*30)